<?php

/**
 * Implements hook_libraries_info().
 */
function commerce_taxcloud_libraries_info() {
  $libraries['php-taxcloud'] = array(
    'name' => 'PHP-TaxCloud',
    'vendor url' => 'https://github.com/VeggieMeat/php-taxcloud',
    'download url' => 'https://github.com/VeggieMeat/php-taxcloud/archive/master.tar.gz',
    'version' => 'dev',
    'files' => array(
      'php' => array(
        'lib/php-taxcloud.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_permission().
 */
function commerce_taxcloud_permission() {
  return array(
    'administer taxcloud settings' => array(
      'title' => t('Administer TaxCloud settings'),
      'description' => t('Access to edit TaxCloud account settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function commerce_taxcloud_menu() {
  $items['admin/commerce/config/taxcloud'] = array(
    'title' => 'Tax Cloud Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_taxcloud_admin_form'),
    'access arguments' => array('administer taxcloud settings'),
    'file' => 'commerce_taxcloud.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function commerce_taxcloud_communication($customer_address, $products, $cartid) {
  if (!class_exists('\TaxCloud\Client')) {
    libraries_load('php-taxcloud');
  }

  $client = new \TaxCloud\Client();

  $destination = new \TaxCloud\Address();
  $destination->setAddress1($customer_address['thoroughfare']);

  if (isset($customer_address['premise'])) {
    $destination->setAddress2($customer_address['premise']);
  }

  $destination->setCity($customer_address['locality']);
  $destination->setState($customer_address['administrative_area']);

  $zip = explode('-', $customer_address['postal_code']);
  $destination->setZip5($zip[0]);
  if (isset($zip[1])) {
    $destination->setZip4($zip[1]);
  }

  $params = array(
    'uspsUserID' => variable_get('commerce_taxcloud_usps_id'),
    'address1' => $destination->getAddress1(),
    'address2' => $destination->getAddress2(),
    'city' => $destination->getCity(),
    'state' => $destination->getState(),
    'zip5' => $destination->getZip5(),
    'zip4' => $destination->getZip4(),
  );

  $VerifyAddress = new \TaxCloud\VerifyAddress(variable_get('commerce_taxcloud_usps_id', $destination));

  $verifiedAddress = $client->VerifyAddress($VerifyAddress);

  if ($verifiedAddress->VerifyAddressResult->ErrNumber == 0) {
    $destination->setAddress1($verifiedAddress->VerifyAddressResult->Address1);
    if (isset($verifiedAddress->VerifyAddressResult->Address2)) {
      $destination->setAddress2($verifiedAddress->VerifyAddressResult->Address2);
    }
    $destination->setCity($verifiedAddress->VerifyAddressResult->City);
    $destination->setState($verifiedAddress->VerifyAddressResult->State);
    $destination->setZip5($verifiedAddress->VerifyAddressResult->Zip5);
    $destination->setZip4($verifiedAddress->VerifyAddressResult->Zip4);
  }

  $origin = new \TaxCloud\Address(
    variable_get('commerce_taxcloud_address1'),
    variable_get('commerce_taxcloud_address2'),
    variable_get('commerce_taxcloud_city'),
    variable_get('commerce_taxcloud_state')
  );

  $zip = explode('-', variable_get('commerce_taxcloud_zip'));
  $origin->setZip5($zip[0]);
  $origin->setZip4($zip[1]);

  foreach ($products as $k => $product) {
    $cartItem = new CartItem();

    $cartItem->setItemID($product['productid']);
    $cartItem->setIndex($product['cart_item_index']);
    // @TODO Set TIC per product type
    $cartItem->setTIC(variable_get('commerce_taxcloud_tic_id', '00000'));
    $cartItem->setPrice($product['price']);
    $cartItem->setQty($product['qty']);

    $cartItems[$k] = $cartItem;
  }

  global $user;

  $lookup = new \TaxCloud\Lookup(
    variable_get('commerce_taxcloud_api_id'),
    variable_get('commerce_taxcloud_api_key'),
    $user->uid,
    $cartid,
    $cartItems,
    $origin,
    $destination
  );

  $lookupResponse = $client->Lookup($lookup);

  $taxes = array();
  $cart_items = $lookupResponse->LookupResult->CartItemsResponse->CartItemResponse;
  if (is_array($cart_items)) {
    foreach ($cart_items as $cart_item) {
      $taxes[$cart_item->CartItemIndex] = $cart_item->TaxAmount;
    }
  }
  elseif (is_object($cart_items)) {
    $taxes[$cart_items->CartItemIndex] = $cart_items->TaxAmount;
  }

  return $taxes;
}

function commerce_taxcloud_authorized_captured($cartid, $products, $orderid) {
  if (!class_exists('\TaxCloud\Client')) {
    libraries_load('php-taxcloud');
  }

  $client = new \TaxCloud\Client();

  foreach ($products as $k => $product) {
    $cartItem = new \TaxCloud\CartItem();

    $cartItem->setItemID($product['productid']);
    $cartItem->setIndex($product['cart_item_index']);
    // @TODO Set TIC per product type.
    $cartItem->setTIC(variable_get('commerce_taxcloud_tic_id', '00000'));
    $cartItem->setPrice($product['price']);
    $cartItem->setQty($product['qty']);

    $cartItems[$k] = $cartItem;
  }

  global $user;

  $authcap = new \TaxCloud\AuthorizedWithCapture(
    variable_get('commerce_taxcloud_api_id'),
    variable_get('commerce_taxcloud_api_key'),
    $user->uid,
    $cartid,
    $cartItems,
    $orderid,
    date("c"),
    date("c")
  );

  $authResponse = $client->AuthorizedWithCapture($authcap);
}
